### ISSUE TITLE
Corregir

### ISSUE THREAD

**Issue by jackievivianv** [4GeeksAcademy/cgravina-clase2-IG-post-con-Bootstrap#1]
Hola Camille, ¡la práctica en general está genial! Solo hay unas cositas que arreglar. 

1) Por ejemplo, el dropdown del navbar no se ve cuando estás en pantalla normal, porque se despliega hacia la derecha. 

2) Y en responsive, cuando el menú se hace una hamburguesa al abrirlo, se abre con el logo también y no debería ser así. El logo debe estar a un lado y la hamburguesa en la esquina del otro lado. 

3) Además, el navbar no debe estar dentro del div container, porque sino aparece con unos márgenes blancos y debería ocupar toda la pantalla. 

4) En el modo móvil, en las tarjetas de los posts individuales lo numeritos de la esquina derecha se pegan al título del post. 

Porfa corrige estas cosas cuando puedas y vuélvelo a subir.

**Comment by cpgravina** [comment]
Hola Jackie! Genial, gracias por los feedback. Ya esta todo corregido! :)
